
--- SETUP CAS2_COURT_BAIL_REFERRER_USER user
CREATE USER IF NOT EXISTS DA_TEST_USER password 'password123456';

-- ensure the staff_ids match
INSERT INTO STAFF_MEMBERS (STAFF_ID, FIRST_NAME, LAST_NAME, STATUS) VALUES (3040, 'CAS2', 'Court Bail Referrer', 'ACTIVE');
INSERT INTO STAFF_USER_ACCOUNTS (username, staff_user_type, staff_id, working_caseload_id, id_source)
VALUES ('DA_TEST_USER', 'GENERAL', 3040, 'LEI', 'USER');

INSERT INTO DBA_USERS (username, account_status, profile)
VALUES ('DA_TEST_USER', 'OPEN', 'TAG_GENERAL');

INSERT INTO SYS.USER$ (name, spare4)
VALUES ('DA_TEST_USER', 'S:C59371608F601E454682E0B5293F2752A1DC31C4BDEF9D50802212AD981E');

INSERT INTO USER_ACCESSIBLE_CASELOADS (CASELOAD_ID, USERNAME, START_DATE) VALUES ('NWEB', 'DA_TEST_USER', now());

INSERT INTO USER_CASELOAD_ROLES (ROLE_ID, CASELOAD_ID, USERNAME) VALUES ((SELECT ROLE_ID FROM OMS_ROLES WHERE ROLE_CODE = 'LICENCE_CA'), 'NWEB', 'DA_TEST_USER');

-- add new role and assign to the user
INSERT INTO OMS_ROLES (ROLE_ID, ROLE_CODE, ROLE_NAME, ROLE_TYPE, ROLE_FUNCTION, ROLE_SEQ, PARENT_ROLE_CODE, SYSTEM_DATA_FLAG) values (ROLE_ID.nextval, 'CAS2_COURT_BAIL_REFERRER', 'CAS2_COURT_BAIL_REFERRER', 'APP', 'ADMIN', 1, null, 'Y');
INSERT INTO USER_CASELOAD_ROLES (ROLE_ID, CASELOAD_ID, USERNAME) VALUES ((SELECT ROLE_ID FROM OMS_ROLES WHERE ROLE_CODE = 'CAS2_COURT_BAIL_REFERRER'), 'NWEB', 'DA_TEST_USER');
