INSERT INTO STAFF (STAFF_ID, START_DATE, SURNAME, FORENAME, ROW_VERSION, OFFICER_CODE, CREATED_BY_USER_ID,
                   LAST_UPDATED_USER_ID, CREATED_DATETIME, LAST_UPDATED_DATETIME, PRIVATE, PROBATION_AREA_ID)
VALUES
    (10200,to_date('01-JAN-18','DD-MON-RR'),'Smith','John',1,'AP00001',1,
     1,to_date('01-JAN-18','DD-MON-RR'),to_date('01-JAN-18','DD-MON-RR'),0,(SELECT probation_area_id FROM PROBATION_AREA WHERE CODE = 'N58'));

Insert into USER_ (USER_ID, STAFF_ID, SURNAME, FORENAME, NOTES, ROW_VERSION,DISTINGUISHED_NAME, PRIVATE, ORGANISATION_ID)
values
    (10200, 10200, 'Smith', 'John', null, 5, 'john-smith', 0, 0);

