Insert into USER_ (USER_ID, STAFF_ID, PROVIDER_EMPLOYEE_ID, SURNAME, FORENAME, FORENAME2, END_DATE, NOTES, ROW_VERSION,
                   DISTINGUISHED_NAME, EXTERNAL_PROVIDER_EMPLOYEEFLAG, EXTERNAL_PROVIDER_ID, TRAINING_SESSION_ID,
                   PRIVATE, ORGANISATION_ID, SC_PROVIDER_ID, CREATED_BY_USER_ID, CREATED_DATETIME, LAST_UPDATED_USER_ID,
                   LAST_UPDATED_DATETIME)
values (10000, 10000, null, 'Approved', 'PremisesTest', null, null, null, 5, 'APPROVEDPREMISESTESTUSER', null, null, null, 0, 0, null,
        2500040507, to_date('07-JUN-19', 'DD-MON-RR'), 2500082588, to_date('02-OCT-19', 'DD-MON-RR'));

INSERT INTO STAFF (STAFF_ID, START_DATE, SURNAME, END_DATE, FORENAME, ROW_VERSION, FORENAME2, STAFF_GRADE_ID, TITLE_ID, OFFICER_CODE, CREATED_BY_USER_ID,
                   LAST_UPDATED_USER_ID, CREATED_DATETIME, LAST_UPDATED_DATETIME, TRAINING_SESSION_ID, PRIVATE, SC_PROVIDER_ID, PROBATION_AREA_ID)
VALUES (10000,to_date('01-JAN-18','DD-MON-RR'),'Approved',null,'PremisesTest',1,'',1,1,'SH00007',1,1,to_date('01-JAN-18','DD-MON-RR'),to_date('01-JAN-18','DD-MON-RR'),null,0,12,12);
